version: '3'
services:
  prod-tyxb_tymh:
    image: 10.251.26.11:5000/prod-image-tyxb-tymh_interface_openservice_tyxb:20210526
    restart: always
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.3"
          memory: 3000M
      restart_policy:
         condition: on-failure
    ports:
      - "8011:3000"
    container_name: prod-tyxb_tymh
    volumes:
      - /app/logs/prod/python/tymh_interface_openservice_tyxb:/opt/logs
      - /app/logs/prod/python/tymh_interface_openservice_tyxb:/app/python_apps_logs
      - /app/logs/prod/python/tymh_interface_openservice_tyxb:/app/python-apps-logs
    environment:
      - LOG_PREFIX=/opt/logs

